version: '2'
services:
  jobserver:
    build: ./aci-job-server/
    ports:
      - '3000:80'
    volumes:
      - './aci-job-server/logs/:/var/log/uwsgi/app/'
    env_file:
      - ./.env
    networks:
      - my-net
  aci-worker:
    build: ./imageRecognition/
    networks:
          - my-net
    ports:
      - '8000:80'
    depends_on:
      - jobserver
    env_file:
      - ./.env
  aci-ui:
    build: ./demo-aci-image/
    ports:
      - "8080:80"
    networks:
          - my-net
    depends_on:
      - jobserver
    volumes:
      - './demo-aci-image/logs/:/var/log/uwsgi/app/'
    env_file:
      - ./.env

networks:
  my-net:
    driver: bridge