apiVersion: apps/v1beta2
kind: Deployment
metadata:
  name: {{ template "tensorstuff.fullname" . }}-aci-worker 
  labels:
    app: {{ template "tensorstuff.name" . }}
    chart: {{ template "tensorstuff.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  replicas: {{ .Values.worker.replicaCount.aci }}
  selector:
    matchLabels:
      app: {{ template "tensorstuff.name" . }}
      release: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app: {{ template "tensorstuff.name" . }}
        release: {{ .Release.Name }}
    spec:
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.worker.image.repository }}:{{ .Values.worker.image.tag }}"
          imagePullPolicy: {{ .Values.worker.image.pullPolicy }}
          ports:
            - name: http
              containerPort: 80
              protocol: TCP
          env:
            - name: API_BASE_URL
              value: "fi.rbitia.com"
          volumesMounts:
            - mountPath: /app/assets/images
              name: fruitshare
      volumes: 
        - name: {{ .Chart.Name }}
          azureFile:
            secretName: azure-secret
            shareName: fruit
            readOnly: false
      dnsPolicy: ClusterFirst
      nodeSelector:
        kubernetes.io/hostname: virtual-kubelet-myaciconnector-linux
      tolerations:
      - key: azure.com/aci
        effect: NoSchedule
    