apiVersion: v1
kind: Service
metadata:
  name: {{ template "tensorstuff.fullname"-worker . }}
  labels:
    app: {{ template "tensorstuff.name"-worker . }}
    chart: {{ template "tensorstuff.chart"-worker . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    app: {{ template "tensorstuff.name"-worker . }}
    release: {{ .Release.Name }}
