apiVersion: apps/v1beta2
kind: Deployment
metadata:
  name: {{ template "tensorstuff.fullname"-worker . }}
  labels:
    app: {{ template "tensorstuff.name"-worker . }}
    chart: {{ template "tensorstuff.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  replicas: {{ .Values.workerReplicaCount }}
  selector:
    matchLabels:
      app: {{ template "tensorstuff.name"-worker . }}
      release: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app: {{ template "tensorstuff.name"-worker . }}
        release: {{ .Release.Name }}
    spec:
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.workerImage.repository }}:{{ .Values.workerImage.tag }}"
          imagePullPolicy: {{ .Values.workerImage.pullPolicy }}
          ports:
            - name: http
              containerPort: 80
              protocol: TCP
        - env:
            - name: API_BASE_URL
            value: {{ template "tensorstuff.fullname"-worker . }}
