version: '2'
services: 
  redis:
    image: "redis:alpine"
    ports:
      - '6379:6379'
  web:
    build: .
    links:
      - redis
    ports:
      - "80:80"
    depends_on:
      - redis
    volumes:
      - 'C:\Users\sakreter\test\aci-demos\aci-job-server\logs\:/var/log/uwsgi/app/'
