apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: {{ include "fullname" . }}-ir
  labels:
    app: {{ template "name" . }}
    chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  replicas: {{ .Values.imageRecognizer.replicaCount.pods }}
  template:
    metadata:
      labels:
        app: {{ include "fullname" . }}-ir
    spec:
      containers:
        - name: {{ include "fullname" . }}-ir
          image: "{{ .Values.imageRecognizer.image.repository }}:{{ .Values.imageRecognizer.image.tag }}"
          imagePullPolicy: "{{ .Values.imageRecognizer.image.pullPolicy }}"
          env:        
          - name: API_BASE_URL,
            value: "http://rbitia"  
          volumeMounts:
          - mountPath: /app/assets/images
            name: fruitshare
      volumes:
      - name: fruitshare
        azureFile:
          shareName: fruitshare
          secretName: picture-secret
       dnsPolicy: ClusterFirst
      nodeName: virtual-kubelet-myaciconnector-linux 
      tolerations:
      - key: azure.com/aci
        effect: NoSchedule
    
